// A large, diverse list of evergreen search queries to be used when the Google Trends API fails.
const fallbackQueries = [
    "how to tie a tie",
    "best chocolate chip cookie recipe",
    "how to take a screenshot on mac",
    "what is my ip address",
    "how to lose weight fast",
    "how to cook rice",
    "what time is it",
    "how to boil an egg",
    "how to make pancakes",
    "what does tbh mean",
    "how to change a tire",
    "how many ounces in a cup",
    "how to screenshot on windows",
    "how to meditate",
    "what is the meaning of life",
    "how to make french toast",
    "how to get rid of hiccups",
    "what is love",
    "how to download youtube videos",
    "how to write a resume",
    "what is a vpn",
    "how to check your credit score for free",
    "how to invest in stocks",
    "what are the symptoms of covid-19",
    "how to start a blog",
    "how to build a pc",
    "what is the weather today",
    "how to cook salmon",
    "what is my zodiac sign",
    "how to make a margarita",
    "how to get rid of ants",
    "what is the capital of australia",
    "how to bake a potato",
    "what is inflation",
    "how to grow tomatoes",
    "what is a Roth IRA",
    "how to unclog a drain",
    "how to improve your memory",
    "what is the best way to learn a new language",
    "how to make cold brew coffee",
    "what is a blockchain",

    // Add more queries here until you have a large list
    "easy chicken dinner recipes",
    "at-home workout for beginners",
    "symptoms of vitamin D deficiency",
    "how to grow an avocado tree",
    "best netflix series to watch",
    "how to clean a coffee maker",
    "what is compound interest",
    "how to budget your money",
    "what is the pythagorean theorem",
    "how to change your password",
    "healthy breakfast ideas",
    "how to fix a leaky faucet",
    "what is the difference between a latte and a cappuccino",
    "how to set up a new iphone",
    "what is a good credit score",
    "how to get better sleep",
    "how to remove red wine stains",

    // Continue adding...
    "best dog breeds for families",
    "how to train a puppy",

    "what is photosynthesis",
    "how to write a cover letter",
    "what is the best travel credit card",
    "how to start a fire",
    "what are the seven wonders of the world",
    "how to play chess",
    "what is the stock market",
    "how to make a good first impression",
    "what is artificial intelligence",
    "how to do a push up",
    "what are the benefits of yoga",
    "how to make a website",
    "what is the purpose of a resume",
    "how to be more productive",
    "what is a healthy diet",
    "how to save money on groceries",
    "what is the difference between jail and prison",
    "how to make your own pizza",
    "what is the best way to whiten teeth",
    "how to get rid of fruit flies",
    "what is a synonym for happy",
    "how to make a resume stand out",
    "what is the fastest animal on earth",
    "how to cook a steak",
    "what is the best time to visit hawaii",
    "how to make a paper airplane",
    "what is the most spoken language in the world",
    "how to get rid of bed bugs",
    "what is the best way to get rid of weeds",
    "how to make a compost bin",
    "what is the best way to clean a cast iron skillet",
    "how to make a smoothie",
    "what is the best way to learn guitar",
    "how to make a good cup of coffee",
    "what is the best way to study for a test",
    "how to get rid of dark circles under your eyes",
    "what is the best way to get rid of acne",
    "how to get rid of a headache",
    "what is the best way to get rid of a sore throat",

    "how to unclog a toilet with baking soda",
    "DIY wood pallet furniture ideas",
    "how to paint kitchen cabinets without sanding",
    "best chocolate chip cookie recipe soft and chewy",
    "how to cook salmon perfectly on stovetop",
    "easy chicken stir-fry recipe healthy",
    "symptoms of iron deficiency anemia",
    "full-body home workout routine no equipment",
    "calories in a slice of whole wheat bread",
    "how to convert PDF to Word document free",
    "best noise-cancelling headphones for travel",
    "what is blockchain technology explained simply",
    "how to start investing for beginners",
    "what is a Roth IRA vs Traditional IRA",
    "mortgage payment calculator with taxes and insurance",
    "best hiking trails in the US national parks",
    "how to find cheap flights to Europe",
    "best pizza restaurants near me open now",
    "reviews for the latest robot vacuum cleaner",
    "most comfortable walking shoes for women",
    "best gaming laptops under $1000",
    "what is the solar system's largest planet",
    "simple explanation of photosynthesis for kids",
    "who was the first president of the United States",
    "best classic rock songs of all time",
    "how to learn guitar chords for beginners",
    "top rated fantasy book series to read",
    "what does lol mean in texting",
    "define ephemeral dictionary meaning",
    "what is a metaphor in poetry",
    "how to change oil in a car step-by-step",
    "how often should you rotate car tires",
    "what is antifreeze used for in a car",
    "how to grow avocados from a pit indoors",
    "best low-maintenance indoor plants",
    "how to get rid of weeds in lawn naturally",
    "quick vegetarian lasagna recipe",
    "benefits of meditation for stress relief",
    "how to create a monthly budget plan",
    "best free online courses for coding",
    "effective tips for job interviews",
    "how to write a cover letter example",
    "difference between weather and climate",
    "easy homemade pizza dough recipe no yeast",
    "best stretches for hamstring tightness",
    "how to clean a shower head naturally",
    "ideas for organizing a small bedroom closet",
    "what is compound interest formula",
    "how to make homemade bath bombs easy",
    "symptoms of the common cold vs flu",
    "best exercises for core strength",
    "how to make money online legally",
    "popular video games for PC",
    "what is cryptocurrency mining",
    "travel insurance comparison guide",
    "best time to visit different countries",
    "what are the health benefits of turmeric",
    "how to get rid of fruit flies quickly",
    "how to fix a leaky faucet sink",
    "what is the Pythagorean theorem used for",
    "define ubiquitous meaning and usage",
    "what is the chemical formula for water",
    "best mystery novels of the 20th century",
    "basic rules of poker explained",
    "popular cooking techniques for meat",
    "healthy breakfast ideas with oatmeal",
    "how to lower blood pressure naturally",
    "guide to buying a used car checklist",
    "how to replace windshield wipers",
    "best perennials for shade garden",
    "simple homemade face mask recipes",
    "how to write a business plan",
    "where to find free stock photos",
    "easy tutorial for knitting a scarf",
    "how to check your credit score for free",
    "best credit cards for cash back rewards",
    "what are mutual funds investing",
    "how to bake a perfect cheesecake",
    "low-carb diet plan for beginners",
    "how to build muscle at home with dumbbells",
    "what is machine learning in AI",
    "how to use google sheets formulas",
    "best ergonomic office chair reviews",
    "what is the difference between a lawyer and an attorney",
    "basic principles of economics",
    "who invented the light bulb",
    "best animated movies for family viewing",
    "rules for playing chess castling",
    "how to make a good cup of coffee at home",
    "what is the definition of photosynthesis",
    "what is an adjective in grammar",
    "how to properly inflate car tires",
    "DIY vertical garden ideas for balcony",
    "when to prune hydrangeas for best bloom",
    "easy lentil soup recipe healthy",
    "how to improve sleep quality naturally",
    "best budgeting apps for couples",
    "popular cloud storage services comparison",
    "how to set up a home Wi-Fi network",
    "what is phishing cyber security",
    "how to calculate federal income tax",
    "guide to refinancing a home mortgage",
    "things to do in London for free",
    "best luggage brands for durability",
    "restaurants with outdoor seating near me",
    "best moisturizer for dry skin reviews",
    "men's leather boots for winter",
    "digital cameras for beginners photography",
    "basic coding concepts for absolute beginners",
    "famous quotes about life and happiness",
    "what is the speed of light in km/s",
    "classic horror movies everyone must see",
    "how to tie a necktie simple knot",
    "what is the average human body temperature",
    "how to get rid of hiccups fast",
    "best way to clean stainless steel appliances",
    "how to store fresh herbs long-term",
    "what is the meaning of life philosophy",
    "DIY paper flower tutorial easy",
    "what is the greenhouse effect explained",
    "easy lemon chicken marinade recipe",
    "how to deal with anxiety naturally",
    "best debit cards for travelers",
    "popular social media platforms statistics",
    "how to clear browser cache and cookies",
    "what is the dark web internet",
    "stock market basics for dummies",
    "how to open a brokerage account online",
    "best places to retire on a budget",
    "list of UNESCO world heritage sites",
    "where to buy organic groceries near me",
    "best essential oils for stress relief",
    "how to propagate succulents from leaves",
    "difference between alligators and crocodiles",
    "what are the main types of poetry",
    "how to parallel park a car tutorial",
    "common signs of a bad car battery",
    "best indoor trees for low light",
    "easy shrimp scampi recipe with pasta",
    "yoga poses for lower back pain relief",
    "how to save money on electricity bill",
    "best anti-virus software reviews",
    "how to build a website with wordpress",
    "what is augmented reality AR",
    "history of the Roman Empire timeline",
    "famous female scientists and their discoveries",
    "best board games for adults party",
    "how to memorize things quickly and easily",
    "easy homemade salad dressing recipes",
    "how to boost immune system naturally",
    "what is inflation and how does it work",
    "best travel destinations for solo female travelers",
    "where to find free online books",
    "how to write a compelling resume summary",
    "grammar rules for using commas",
    "simple recipe for mashed potatoes fluffy",
    "at-home physical therapy exercises for knees",
    "how to clean mold off walls safe method",
    "DIY picture frame ideas unique",
    "what is the theory of relativity explained",
    "what does IDK mean in texting",
    "define eloquent speaking",
    "what is personification in literature",
    "how to check car fluid levels correctly",
    "best way to clean leather car seats",
    "how to mulch a garden bed properly",
    "best tomato soup recipe from scratch",
    "mindfulness exercises for beginners",
    "best high-yield savings accounts",
    "latest smartphone reviews and comparison",
    "how to secure your home Wi-Fi router",
    "what is a firewall in networking",
    "guide to opening a checking account online",
    "how to calculate simple interest",
    "best budget travel destinations in Asia",
    "list of 7 wonders of the ancient world",
    "local farmers markets near me schedule",
    "best sunscreens for sensitive skin",
    "durable backpacks for college students",
    "how to choose a laptop for graphic design",
    "what is quantum computing explained",
    "fun facts about the human body",
    "what is the difference between mass and weight",
    "famous playwrights and their works",
    "how to play the ukulele basic chords",
    "easy cocktail recipes with vodka",
    "healthy smoothie recipes for weight loss",
    "how to increase metabolism naturally",
    "best time to buy airline tickets",
    "how to use a VPN for streaming",
    "what is the difference between a hard drive and SSD",
    "how to create a budget spreadsheet",
    "best retirement living communities",
    "how to install a floating shelf",
    "best ways to organize kitchen drawers",
    "homemade bug repellent for garden",
    "easy pad thai recipe authentic",
    "benefits of drinking green tea",
    "how to improve your public speaking skills",
    "what is cloud computing services",
    "how to remove wine stains from carpet",
    "what is the meaning of democracy",
    "how to write a thank you note professionally",
    "simple explanation of gravity",
    "best historical fiction novels",
    "how to whistle with your fingers",
    "what is the difference between an allergy and intolerance",
    "how to remove rust from metal tools",
    "how to clean grout between tiles",
    "DIY homemade natural cleaning products",
    "best vegan chili recipe easy",
    "guided meditation for deep sleep",
    "how to save for a down payment on a house",
    "best personal finance books for beginners",
    "how to change your phone battery",
    "what is 5G network technology",
    "cheap weekend getaway ideas near me",
    "best noise-cancelling earbuds for sleeping",
    "what are common symptoms of stress",
    "how to treat a minor burn at home",
    "how to clean a greasy stove top",
    "best perennial flowers for sunny areas",
    "easy beef stew recipe slow cooker",
    "how to choose the right running shoes",
    "best website builders for small business",
    "how to protect your identity online",
    "famous speeches that changed the world",
    "who wrote the play Romeo and Juliet",
    "how to fold a fitted sheet easily",
    "best way to store potatoes long term",
    "what is Stoicism philosophy basics",
    "easy craft ideas for adults",
    "how to pronounce difficult English words",
    "what is the formula for area of a circle",
    "how to write a professional memo",
    "difference between gross and net income",
    "healthy recipes for air fryer chicken",
    "what are the signs of dehydration",
    "how to do a basic oil change yourself",
    "best winter tires for snow and ice",
    "how to revive a dying houseplant",
    "simple recipe for homemade hummus",
    "stretching routine for morning stiffness",
    "how to get approved for a personal loan",
    "latest smartwatches reviews 2024",
    "how to use keyboard shortcuts effectively",
    "what is the internet of things IoT",
    "guide to filling out tax forms for beginners",
    "best cities in Europe to visit in winter",
    "local dog parks near me directions",
    "best vitamin C serum for face",
    "men's casual jackets for fall",
    "how to choose a mountain bike size",
    "what is the periodic table of elements",
    "how to write a bibliography MLA format",
    "famous paintings and their artists",
    "best podcasts for learning history",
    "how to play the harmonica basic notes",
    "easy dessert recipes no bake",
    "best time to eat for weight loss",
    "how to get rid of a headache without medicine",
    "how to repair drywall holes small",
    "DIY storage solutions for small apartments",
    "what is the butterfly effect meaning",
    "easy recipe for homemade vegetable broth",
    "how to deal with difficult people at work",
    "best banks for checking accounts",
    "how to reset a forgotten Windows password",
    "what is two-factor authentication",
    "investment strategies for long-term growth",
    "how to pack a backpack for backpacking trip",
    "best noise-cancelling earplugs for sleeping",
    "how to know if you have a fever",
    "how to clean kitchen sink drain naturally",
    "best way to store carrots and celery",
    "what are the different types of clouds",
    "how to write a good poem structure",
    "difference between plasma and LCD TV",
    "how to clean an oven with natural ingredients",
    "best flowers to attract hummingbirds",
    "easy baked potato recipe toppings",
    "beginner's guide to running a 5k",
    "how to use a multimeter electrical tester",
    "what is the deep web vs dark web",
    "how to calculate compound annual growth rate",
    "best international travel credit cards",
    "most beautiful national parks in the world",
    "local coffee shops near me with free Wi-Fi",
    "best natural shampoos for hair loss",
    "women's waterproof hiking boots reviews",
    "latest video game console comparison",
    "what is the scientific method steps",
    "famous historical figures biographies",
    "best strategy board games for two players",
    "how to stop procrastination habits",
    "easy baked goods recipes for beginners",
    "health benefits of yoga daily",
    "how to improve communication skills",
    "what is a blockchain wallet",
    "how to remove super glue from skin",
    "what is the difference between a planet and a star",
    "easy chili con carne recipe",
    "stretches for hip flexor pain",
    "how to clean hardwood floors without streaks",
    "DIY essential oil diffuser blends",
    "what is quantum entanglement explained",
    "what does FOMO mean in slang",
    "define pragmatic approach",
    "what is an oxymoron with examples",
    "how to check your car's oil level",
    "best floor jacks for home garage",
    "how to care for indoor herb garden",
    "simple chicken and rice recipe healthy",
    "best supplements for energy and focus",
    "how to apply for a student loan",
    "how to backup phone data to computer",
    "what is serverless computing",
    "difference between stocks and bonds",
    "best time to visit national parks",
    "things to do in Paris for first-timers",
    "best budget face wash for oily skin",
    "men's dress shirts non-iron reviews",
    "best drones for beginners with camera",
    "basic principles of physics laws",
    "how to write a research paper outline",
    "famous classical music composers",
    "how to play simple songs on piano",
    "easy chocolate fudge recipe microwave",
    "how to reduce cholesterol naturally",
    "best home security systems without subscription",
    "how to write a formal resignation letter",
    "what is the difference between affect and effect grammar",
    "homemade chicken noodle soup recipe",
    "gentle exercises for neck pain relief",
    "how to remove pet hair from furniture",
    "best plants for office desk low light",
    "what is the theory of evolution explained",
    "what does NSFW stand for online",
    "define benevolent person",
    "what is foreshadowing in a story",
    "how to repair minor car scratches",
    "best car battery brands reviews",
    "how to grow roses from cuttings",
    "easy stir fry sauce recipe",
    "guide to intermittent fasting for beginners",
    "how to create a budget spreadsheet for personal use",
    "best investment apps for beginners",
    "latest virtual reality headsets reviews",
    "how to install a printer on windows 10",
    "what is ethical hacking",
    "how to file an extension for taxes",
    "best budget hotels in New York City",
    "local bookstores near me new and used",
    "best foundations for mature skin",
    "women's winter coats long",
    "best mirrorless cameras for photography",
    "basic principles of chemistry",
    "how to write a cover letter for a job application",
    "famous poets and their most known works",
    "how to tune a guitar standard tuning",
    "easy brownies recipe fudgy",
    "home remedies for acid reflux relief",
    "best way to clean windows without streaks",
    "how to remove wallpaper glue residue",
    "DIY natural air freshener spray",
    "what is the scientific term for the study of animals",
    "easy fish tacos recipe healthy",
    "best time to water lawn and garden",
    "how to get rid of mosquitoes in yard",
    "how to calculate net present value NPV",
    "best laptops for programming students",
    "what is artificial neural network",
    "how to apply for a passport for the first time",
    "best places to see the Northern Lights",
    "local gyms near me with swimming pool",
    "best retinol serum for anti-aging",
    "men's athletic shorts for running",
    "how to choose a monitor for graphic design",
    "what is the Big Bang theory explained",
    "how to cite a website in APA format",
    "famous historical quotes about leadership",
    "how to play the violin for beginners",
    "easy vegetarian curry recipe coconut milk",
    "health benefits of eating nuts daily",
    "how to build an emergency fund quickly",
    "best online tutoring services for math",
    "what is cloud storage and how does it work",
    "how to optimize your website for search engines",
    "what is a cryptocurrency exchange",
    "how to save money on utility bills",
    "DIY coffee scrub for face and body",
    "what is the difference between a city and a town",
    "easy homemade ice cream recipe no machine",
    "how to start running without getting tired",
    "best way to clean a carpet with baking soda",
    "how to remove permanent marker from wood",
    "best natural remedies for a sore throat",
    "how to apply for unemployment benefits",
    "latest home assistant devices reviews",
    "how to connect a bluetooth speaker",
    "what is a virtual private server VPS",
    "how to calculate retirement savings needed",
    "best Caribbean islands for families",
    "popular tourist attractions in Rome",
    "best moisturizers for oily acne-prone skin",
    "women's work pants comfortable",
    "best action cameras for vlogging",
    "basic principles of psychology",
    "how to write a college essay effectively",
    "famous scientists and their inventions",
    "best fiction books of the 21st century",
    "how to play simple songs on guitar",
    "easy pancake recipe from scratch buttermilk",
    "how to boost energy without caffeine",
    "best way to clean a microwave oven",
    "how to repair a leaky toilet flapper",
    "DIY bird feeder plans",
    "what is the meaning of existence philosophy",
    "easy homemade coleslaw recipe",
    "how to improve your memory and concentration",
    "best travel rewards credit cards",
    "how to clear cache on Android phone",
    "what is a denial of service attack DoS",
    "how to diversify investment portfolio",
    "best places to live in the USA for job growth",
    "things to do in Tokyo off the beaten path",
    "best anti-dandruff shampoo for men",
    "men's casual shoes for walking",
    "best beginner telescopes for astronomy",
    "what are the different forms of energy",
    "how to write a persuasive essay",
    "famous philosophers and their ideas",
    "best documentaries on Netflix right now",
    "how to shuffle cards like a pro",
    "easy baked chicken breast recipes healthy",
    "full body stretching routine for flexibility",
    "how to clean a dishwasher with vinegar",
    "best way to organize a pantry small space",
    "what is the theory of general relativity",
    "what does YOLO mean in social media",
    "define poignant story",
    "what is alliteration in writing",
    "how to check tire pressure correctly",
    "best roof racks for car travel",
    "how to prune fruit trees in winter",
    "easy banana bread recipe moist",
    "how to overcome social anxiety tips",
    "best budgeting methods for college students",
    "latest smart home devices reviews",
    "how to set up dual monitors",
    "what is a distributed ledger technology DLT",
    "how to calculate capital gains tax",
    "best solo travel destinations for safety",
    "local breweries near me with food",
    "best electric toothbrush reviews",
    "women's running leggings with pockets",
    "best video editing software for beginners",
    "what are the layers of the Earth",
    "how to write a formal invitation letter",
    "famous landmarks in the world list",
    "best murder mystery books of all time",
    "how to play checkers rules",
    "easy homemade frosting recipe vanilla",
    "health benefits of apple cider vinegar",
    "how to repair a running toilet constantly",
    "DIY wall art ideas canvas",
    "what is the definition of irony",
    "easy homemade waffles recipe fluffy",
    "how to increase focus while studying",
    "best money market accounts rates",
    "latest e-reader reviews and comparison",
    "how to set up parental controls on tablet",
    "what is open-source software",
    "how to calculate sales tax rate",
    "best all-inclusive resorts for couples",
    "local dog friendly cafes near me",
    "best hair dryer for fine hair reviews",
    "men's casual shirts long sleeve",
    "best desktop computers for home use",
    "basic principles of geology",
    "how to write a compelling personal statement",
    "famous historical battles timeline",
    "best poetry books for beginners",
    "how to read sheet music basic notes",
    "easy meatloaf recipe classic",
    "best exercises for bad knees",
    "how to clean a coffee maker with vinegar",
    "how to remove stains from plastic containers",
    "DIY natural facial scrub recipe",
    "what is the concept of yin and yang",
    "easy slow cooker pork chop recipe",
    "how to manage work-life balance effectively",
    "best online stock brokers for beginners",
    "how to troubleshoot common computer problems",
    "what is virtual reality VR vs AR",
    "how to open a small business bank account",
    "best European cities to visit in summer",
    "popular tourist destinations in the United States",
    "best facial cleanser for sensitive skin",
    "women's ankle boots comfortable",
    "best headphones for working out",
    "basic concepts of biology",
    "how to write an argumentative essay structure",
    "famous inventors and their biggest inventions",
    "best science fiction movies of all time",
    "how to tie a bow tie tutorial",
    "easy homemade soup recipes vegetarian",
    "home remedies for dry scalp and dandruff",
    "how to clean and season a cast iron skillet",
    "best way to organize a linen closet",
    "what is existentialism philosophy basics",
    "DIY holiday gift ideas homemade",
    "what is the difference between a rock and a mineral",
    "easy healthy baked chicken recipes",
    "how to improve your negotiation skills",
    "best banks for free checking accounts",
    "how to fix a slow computer performance",
    "what is a proxy server network",
    "how to pay off credit card debt fast",
    "best romantic getaways in the mountains",
    "list of capital cities of the world",
    "local car wash near me prices",
    "best anti-aging creams for neck",
    "men's athletic compression shorts",
    "best gaming headsets for PC",
    "basic principles of sociology",
    "how to write a strong thesis statement",
    "famous literary quotes about love",
    "best acoustic songs for guitar beginners",
    "easy apple crisp recipe with oatmeal topping",
    "stretches for lower back and sciatica pain",
    "how to clean and restore wood furniture",
    "how to remove rust from clothing",
    "DIY raised garden bed plans",
    "what is the Heisenberg uncertainty principle",
    "what does SFW stand for meaning",
    "define esoteric knowledge",
    "what is a paradox in logic",
    "how to properly winterize a car",
    "best tire pressure gauge digital",
    "how to care for indoor bonsai tree",
    "simple homemade beef jerky recipe",
    "how to boost self-confidence and self-esteem",
    "best way to save money on gas",
    "latest tablets reviews for students",
    "how to delete temporary files on windows",
    "what is blockchain technology used for",
    "how to create a personal financial statement",
    "best cruise lines for families with kids",
    "local ice cream shops near me menu",
    "best anti-acne spot treatments",
    "women's business professional attire",
    "best portable speakers for outdoor use",
    "basic concepts of ecology",
    "how to write a formal business letter",
    "famous battles of World War II",
    "best family movies for a movie night",
    "how to solve a Rubik's cube 3x3",
    "easy salmon recipes healthy baked",
    "how to reduce joint pain naturally",
    "best budgeting app for tracking expenses",
    "how to change default browser settings",
    "what is cryptocurrency staking",
    "how to improve your concentration at work",
    "DIY sugar scrub recipe for body",
    "what is the difference between a state and a nation",
    "easy chocolate mousse recipe no eggs",
    "best stretches for desk workers",
    "how to clean a brick fireplace interior",
    "how to remove water stains from wood furniture",
    "best natural remedies for a stuffy nose",
    "how to apply for a mortgage pre-approval",
    "latest streaming devices comparison",
    "how to use a vpn on phone",
    "what is a ransomware attack",
    "guide to investing in index funds",
    "best cities in the world to visit alone",
    "local hiking trails near me easy",
    "best natural hair dye brands",
    "men's hiking boots waterproof",
    "best smart scales for weight loss",
    "what is the meaning of the word 'amalgamate'",
    "how to write a formal apology letter",
    "famous composers of the Renaissance era",
    "best thriller books of the 21st century",
    "how to play the banjo for beginners",
    "easy homemade apple pie recipe classic",
    "best foods for brain health and memory",
    "how to clean tile and grout in bathroom",
    "how to repair a hole in the wall drywall",
    "DIY homemade hand sanitizer recipe",
    "what is the Doppler effect explained",
    "what does TMI mean in conversation",
    "define zealous behavior",
    "what is hyperbole with examples",
    "how to jump start a motorcycle",
    "best car phone mount for dash",
    "how to grow strawberries in pots",
    "easy vegetable curry recipe quick",
    "best vitamins for skin health",
    "how to improve your credit score fast",
    "latest smart TVs reviews 2024",
    "how to optimize your phone battery life",
    "what is a computer virus and how to prevent it",
    "how to calculate compound interest monthly",
    "best beaches in the world for surfing",
    "list of endangered species worldwide",
    "local bakeries near me best bread",
    "best lightweight foundation for summer",
    "women's running jackets waterproof",
    "best home security cameras outdoor wireless",
    "basic concepts of anatomy and physiology",
    "how to write a good introduction paragraph",
    "famous works of literature by women",
    "best books on personal development",
    "how to play the ukulele songs easy",
    "easy baked goods recipes with bananas",
    "how to treat minor cuts and scrapes at home",
    "best way to clean a microwave with lemon",
    "how to remove oil stains from clothes",
    "DIY pallet wall decor ideas",
    "what is the golden ratio explained",
    "easy homemade pasta dough recipe",
    "how to set professional goals for career growth",
    "best online brokerage accounts for retirement",
    "how to fix a laptop that won't turn on",
    "what is the role of an operating system",
    "how to calculate effective annual rate",
    "best places to visit in the Caribbean",
    "things to do in Chicago for tourists",
    "best tinted moisturizer with SPF",
    "men's casual jackets for spring",
    "best drone photography tips for beginners",
    "what is the difference between kinetic and potential energy",
    "how to write a persuasive speech outline",
    "famous women in history and their impact",
    "best board games for couples",
    "how to learn a new language fast",
    "easy chocolate lava cake recipe",
    "how to do a basic full-body stretch routine",
    "best way to clean a washing machine with bleach",
    "how to organize a refrigerator efficiently",
    "what is the Socratic method of questioning",
    "DIY essential oil recipes for cleaning",
    "what is the difference between a moth and a butterfly",
    "easy homemade macaroni and cheese recipe",
    "best exercises for posture correction",
    "how to invest in real estate for beginners",
    "latest video cards for gaming reviews",
    "how to secure your laptop against theft",
    "what is a virtual machine VM",
    "how to calculate debt-to-income ratio",
    "best destinations for budget backpacking",
    "local farmers markets near me today",
    "best facial oils for glowing skin",
    "women's dress shoes for work comfort",
    "best home projectors for movie night",
    "basic principles of trigonometry",
    "how to write a personal biography sample",
    "famous explorers and their discoveries",
    "best fantasy movies of all time",
    "how to play simple songs on ukulele",
    "easy no-bake cheesecake recipe",
    "how to naturally detox your body at home",
    "best way to remove pet odors from carpet",
    "how to clean blinds easy method",
    "DIY sugar scrub recipe for feet",
    "what is the meaning of deja vu",
    "easy baked ziti recipe with ricotta",
    "how to improve problem-solving skills",
    "best credit cards for excellent credit",
    "how to update device drivers on windows",
    "what is artificial general intelligence AGI",
    "how to calculate return on investment ROI",
    "best places to retire abroad cheap",
    "list of endangered animals in North America",
    "local coffee roasters near me wholesale",
    "best hair masks for damaged hair",
    "men's business casual shoes leather",
    "best wireless keyboards and mice combo",
    "basic concepts of statistics probability",
    "how to write a resignation letter with notice",
    "famous art movements and their characteristics",
    "best motivational books for self-improvement",
    "how to read music notes for piano",
    "easy homemade apple butter recipe slow cooker",
    "how to treat a sprained ankle at home",
    "best way to clean wooden deck",
    "how to remove rust from clothes",
    "DIY mosaic tile projects for beginners",
    "what is the theory of chaos explained",
    "what does ATM stand for banking",
    "define altruistic behavior",
    "what is a semicolon used for in writing",
    "how to fix a slow drain in bathtub",
    "best car wash soap reviews",
    "how to grow basil indoors in water",
    "simple chicken pot pie recipe easy",
    "best protein powder for muscle gain",
    "how to negotiate a lower credit card interest rate",
    "latest laptops for students reviews",
    "how to factory reset an iPhone",
    "what is data mining and analysis",
    "how to calculate loan amortization schedule",
    "best family vacation spots in Florida",
    "things to do in San Francisco for families",
    "best drugstore mascara reviews",
    "women's winter boots waterproof",
    "best fitness trackers for cycling",
    "basic concepts of meteorology",
    "how to write a good conclusion paragraph",
    "famous quotes about friendship",
    "best mystery TV shows of all time",
    "how to learn basic sign language",
    "easy sugar cookie recipe cutouts",
    "home remedies for poison ivy rash",
    "how to clean baseboards effectively",
    "how to remove stains from marble countertop",
    "DIY natural laundry detergent recipe",
    "what is the scientific term for the study of insects",
    "easy baked salmon recipes lemon garlic",
    "how to manage chronic pain naturally",
    "best personal finance podcasts",
    "how to set up a small home office",
    "what is a secure socket layer SSL",
    "how to create a budget for travel",
    "best solo travel destinations for nature lovers",
    "list of famous waterfalls in the world",
    "local craft breweries near me events",
    "best facial steamers for home use",
    "men's waterproof jackets for hiking",
    "best smart light bulbs reviews",
    "basic concepts of philosophy ethics",
    "how to write a persuasive memo",
    "famous explorers of the sea",
    "best thriller movies of the 21st century",
    "how to play the harmonica blues",
    "easy homemade cookie recipes",
    "how to lower cholesterol without medication",
    "best way to clean a chimney flue",
    "how to remove candle wax from carpet",
    "DIY floating TV stand ideas",
    "what is the Fermi paradox explained",
    "what does NSFW mean in gaming",
    "define meticulous detail",
    "what is an apostrophe used for in grammar",
    "how to properly inflate bike tires",
    "best portable jump starters for car",
    "how to grow indoor microgreens",
    "simple lentil soup recipe for weight loss",
    "best natural remedies for insomnia",
    "how to improve your credit score after bankruptcy",
    "latest 4K monitors for gaming reviews",
    "how to backup computer to external hard drive",
    "what is quantum supremacy",
    "how to calculate compound interest daily",
    "best family resorts in the Caribbean",
    "things to do in Los Angeles for free",
    "best hyaluronic acid serum for hydration",
    "women's casual sneakers for walking",
    "best instant cameras reviews",
    "basic concepts of oceanography",
    "how to write a formal complaint letter",
    "famous scientists and their quotes",
    "best romantic comedies of all time",
    "how to play the drums for beginners",
    "easy fried rice recipe chinese style",
    "stretches for upper back and shoulder pain",
    "how to clean a window air conditioner unit",
    "how to organize a garage on a budget",
    "what is the concept of nihilism",
    "DIY essential oil blends for sleep",
    "what is the difference between lava and magma",
    "easy homemade chili recipe",
    "how to improve critical thinking skills",
    "best credit cards for bad credit",
    "how to troubleshoot internet connection problems",
    "what is a blockchain hash",
    "how to invest in stocks for beginners",
    "best places to visit in the Mediterranean",
    "list of natural wonders of the world",
    "local yoga studios near me classes",
    "best facial sunscreen for sensitive skin",
    "men's formal dress shoes oxford",
    "best projectors for business presentations",
    "basic concepts of anthropology",
    "how to write a professional email subject line",
    "famous battles of the American Civil War",
    "best animated movies of the last decade",
    "how to play the ocarina notes",
    "easy banana bread recipe with walnuts",
    "best natural remedies for cough",
    "how to clean a wooden cutting board",
    "how to remove rust from driveway concrete",
    "DIY homemade natural deodorant recipe",
    "what is the placebo effect explained",
    "what does RSVP mean in invitations",
    "define resilient person",
    "what is analogy with examples",
    "how to check your car's transmission fluid",
    "best portable air compressors for tires",
    "how to grow carrots in a raised bed",
    "simple vegetarian shepherd's pie recipe",
    "best home remedies for bloating",
    "how to apply for a personal loan online",
    "latest smartphones with best camera",
    "how to encrypt files on windows 10",
    "what is a computer firewall",
    "how to calculate gross profit margin",
    "best European cities to visit in autumn",
    "popular tourist attractions in Canada",
    "best overnight oats recipe healthy",
    "how to improve focus and concentration",
    "how to invest in retirement accounts",
    "best laptops for video editing",
    "what is a data structure in programming",
    "how to write a business email format",
    "famous world leaders biographies",
    "best fiction books of all time",
    "how to play the saxophone for beginners",
    "easy chocolate chip cookie recipe no brown sugar",
    "best stretches for flexibility and mobility",
    "how to clean and shine silver jewelry",
    "how to remove chewing gum from carpet",
    "DIY mason jar crafts for gifts",
    "what is the theory of relativity in space",
    "what does POV mean in video",
    "define concise writing",
    "what is passive voice in grammar",
    "how to clean car headlights foggy",
    "best dash cams for Uber drivers",
    "how to plant tulip bulbs correctly",
    "simple chicken vegetable soup recipe",
    "how to increase energy levels naturally",
    "best high-yield savings accounts online",
    "latest drones for professional use",
    "how to install a new graphics card",
    "what is a recursive function",
    "how to calculate quarterly tax payments",
    "best honeymoon destinations all-inclusive",
    "local sports bars near me with TV",
    "best vitamin E oil for scars",
    "women's athletic shirts long sleeve",
    "best home rowing machines reviews",
    "basic concepts of political science",
    "how to write a good book report",
    "famous Roman emperors timeline",
    "best comedy movies of all time",
    "how to play the harmonica easy songs",
    "easy homemade ice cream recipes no churn",
    "how to lower blood sugar naturally",
    "best way to clean a refrigerator naturally",
    "how to remove rust from clothes white",
    "DIY spice rack organizer ideas",
    "what is the concept of fate vs free will",
    "easy chicken and broccoli stir fry recipe",
    "how to manage time effectively at work",
    "best index funds for long-term investing",
    "how to troubleshoot laptop battery not charging",
    "what is cloud computing service models",
    "how to create a retirement budget",
    "best national parks to visit in winter",
    "local art galleries near me free",
    "best anti-wrinkle eye cream reviews",
    "men's dress pants slim fit",
    "best action cameras for diving",
    "basic concepts of forensic science",
    "how to write a professional LinkedIn profile summary",
    "famous historical figures of the Renaissance",
    "best young adult fantasy books",
    "how to play the clarinet for beginners",
    "easy homemade apple sauce recipe",
    "health benefits of eating dark chocolate",
    "how to clean a dishwasher filter",
    "how to remove paint from clothing",
    "DIY essential oil blends for focus",
    "what is the definition of gravity in physics",
    "what does IMO mean in chat",
    "define ambivalent feelings",
    "what is simile with examples",
    "how to check car oil and coolant levels",
    "best portable tire inflator for car",
    "how to grow herbs indoors in winter",
    "simple black bean burger recipe homemade",
    "best home remedies for cough and cold",
    "how to get a personal loan with bad credit",
    "latest smartwatches with ECG feature",
    "how to restore factory settings on laptop",
    "what is a quantum computer",
    "how to calculate future value of money",
    "best places to visit in the Caribbean on a budget",
    "list of famous bridges in the world",
    "local thrift stores near me furniture",
    "best facial moisturizer for dry sensitive skin",
    "women's running shoes for trail running",
    "best wireless chargers for phone",
    "basic concepts of sociology culture",
    "how to write a persuasive email",
    "famous scientists who were women",
    "best books on critical thinking",
    "how to play the flute for beginners",
    "easy pumpkin pie recipe from scratch",
    "stretches for flexibility after workout",
    "how to clean a microwave with vinegar and water",
    "how to organize a small kitchen pantry",
    "what is the philosophy of utilitarianism",
    "DIY homemade insect repellent",
    "what is the difference between a galaxy and a universe",
    "easy lentil dahl recipe indian",
    "how to improve decision making skills",
    "best credit repair companies reviews",
    "how to use a vpn for security",
    "what is two-factor authentication setup",
    "how to calculate bond yield to maturity",
    "best places to visit in Southeast Asia",
    "popular tourist attractions in Germany",
    "best face wash for sensitive skin",
    "men's casual jackets for winter",
    "best home audio systems reviews",
    "basic concepts of economics supply and demand",
    "how to write a professional cover letter",
    "famous historical quotes about education",
    "best mystery novels of the 21st century",
    "how to play the cello for beginners",
    "easy cheesecake recipe no bake",
    "home remedies for heartburn relief",
    "how to clean an oven with lemon and baking soda",
    "how to remove wine stains from white shirt",
    "DIY headboard ideas upholstered",
    "what is the meaning of resilience",
    "easy homemade lasagna recipe",
    "how to set SMART goals for personal development",
    "best investment strategies for passive income",
    "how to update firmware on router",
    "what is server virtualization",
    "how to calculate simple rate of return",
    "best family vacation spots in California",
    "local parks near me with trails",
    "best collagen supplements for skin",
    "women's winter coats petite",
    "best smart doorbells reviews",
    "basic concepts of geology plate tectonics",
    "how to write a good college application essay",
    "famous inventors and their lesser known inventions",
    "best comedy TV shows of all time",
    "how to play the clarinet easy songs",
    "easy homemade dinner roll recipe",
    "best foods for healthy hair and skin",
    "how to clean a garbage disposal naturally",
    "how to remove scratches from glass table",
    "DIY natural mouthwash recipe",
    "what is the theory of relativity E=mc^2",
    "what does TLDR mean in articles",
    "define ambiguous meaning",
    "what is a homophone with examples",
    "how to maintain car battery health",
    "best portable tire inflator for bike",
    "how to grow potatoes in a container",
    "simple chicken curry recipe quick",
    "best vitamins for energy boost",
    "how to dispute a charge on credit card",
    "latest noise-cancelling headphones for work",
    "how to use keyboard shortcuts mac",
    "what is machine learning algorithms",
    "how to calculate compound interest quarterly",
    "best romantic beaches in the world",
    "list of capital cities in Europe",
    "local pet stores near me grooming",
    "best tinted lip balm with SPF",
    "men's work boots steel toe",
    "best video projectors for home theater",
    "basic concepts of astronomy black holes",
    "how to write a bibliography Chicago style",
    "famous historical figures of the Enlightenment",
    "best fantasy books of all time",
    "how to play the trumpet for beginners",
    "easy carrot cake recipe moist",
    "stretches for full body flexibility",
    "how to clean a dirty mattress naturally",
    "how to remove rust from clothes colored",
    "DIY pallet swing bed plans",
    "what is the philosophical concept of dualism",
    "easy slow cooker beef ragu recipe",
    "how to improve focus and productivity",
    "best robo-advisors for investing",
    "how to reset network settings on phone",
    "what is a virtual desktop infrastructure VDI",
    "how to calculate future value of an annuity",
    "best solo travel destinations in Europe",
    "popular tourist attractions in Italy",
    "best face mask for blackheads and pores",
    "women's athletic shorts for hiking",
    "best smart thermostats reviews",
    "basic concepts of physics quantum mechanics",
    "how to write a professional cover email",
    "famous battles of the Revolutionary War",
    "best animated movies for adults",
    "how to play the harmonica minor key",
    "easy homemade ice cream recipes with fruit",
    "best foods for a healthy gut",
    "how to clean a shower curtain liner",
    "how to remove glue residue from plastic",
    "DIY homemade air fryer recipes",
    "what is the placebo effect in medicine",
    "what does ASAP mean in business",
    "define pragmatic solution",
    "what is a run-on sentence and how to fix it"
];

module.exports = fallbackQueries;

